Mysql:
  Username: "root"
  Password: "123456"
  Host: "192.168.30.134"
  Port: "3309"
  DB: "toktik"

Redis:
  Host: "192.168.30.134"
  Port: "6379"
  Password: ""
  DB: 1

Token:
  Key: "plKiujmnHBgsYHxJcMhgsJkLsOpaqZec"
  UserTokenExp: 168h # 小时
  AuthorizationKey: why