Server:
  Name: "user"
  RunMode: "DEBUG"
  Addr: "0.0.0.0:8081"
  DefaultContextTimeout: 10s

RPC:
  Name: "rpc-user"
  Addr: "0.0.0.0:8881"


Logger:
  Level: "debug"
  LogSavePath: "storage/applogs/"
  LogFileExt:    ".log"
  MaxSize: 10
  MaxBackups: 7
  MaxAge: 30
  Compress: false
  LowLevelFile: "info"
  HighLevelFile: "error"